### ISSUE TITLE
Hass-entso-e broken after update to 2023.12 does this still work?

### ISSUE THREAD

**Issue by ThorAlex87** [andreas-berg/hass-entsoe-dayahead#1]
Hi! 
So 2023.12 broke hass-entso-e, see my comment here: https://github.com/JaccoR/hass-entso-e/issues/133

Is this version still working normally?

I'll go and try to set it up anyways, but I thought I'd ask in case there is an issue.
Edit: Tried to install, but there seems to be issues because the folder in custom_components have the same name.

**Comment by PdRuiter** [comment]
Same situation here.  Entso-e  did not work anymore after update 2023-12.    Home Assistant complain that he can not find entsoe.  Looking in this issue i understand that entsoe must be in the dir /config/custom_components/..   But it is in the directory /config/custom_components/hacs/entsoe.  Can somebody comment on the fact that it is possible in the wrong directry ??

**Comment by andreas-berg** [comment]
Hi! 
I'm on core-version 2023.12.4 now. This component had a serious cpu-hogging bug until today but I don't think issue JaccoR#133 applies to here, pls correct me if I'm wrong. 
This component is not (yet) on HACS so it's always installed manually in `config/custom_components/entsoe`

**Comment by andreas-berg** [comment]
I think this is not an issue anymore, closing, pls re-open if necessary..
