### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by hanskenb** [andreas-berg/hass-entsoe-dayahead#3]
Hi,
when copying your yaml card configuration I am getting 

bad indentation of a mapping entry (2:10)

 1 | - title: Elpris
 2 |     cards:
--------------^
 3 |       - type: vertical-stack
 4 |         cards:
 
 I have tried to correct it but it then says "no card type found".
 
 I am very new to yaml.

**Comment by andreas-berg** [comment]
Hi, 
yaml is quite sensitive to indentation, I use 2 spaces/level, pls verify that your conf has the right indentation. If it still doesn't work pls share your conf here in (in code-block)

**Comment by andreas-berg** [comment]
I'm simplified the example apexchart-card yaml a little. I'll close this issue now, pls reopen if needed.
