### ISSUE TITLE
Can I drop in replace this fork with the old HACS entsoe integration?

### ISSUE THREAD

**Issue by woytekbode** [andreas-berg/hass-entsoe-dayahead#6]
I actively use today's and tomorrow's prices from the old entsoe integration by JaccoR. I would like to try your fork due to inactivity on the other integration.

What would be best? To replace the files in my existing custom_components/ensoe folder (installed via HACS). Or to create a new integration, next to the old one and then transfer to the new entities? I'm not sure if it's possible to have both running, thanks!

**Comment by pihiandreas** [comment]
Hi, sure you can! It should be possible to run both, but safest to delete the JaccoR version (from HACS if you installed it there) and add this, as you suggested, as custom_component. 
If you need to run both, pls let me know and I'll test/look into possibly necessary changes. 
I admit to not paying enough attention lately to this integration and will try to respond to any further needs swiftly.
Cheers, Andreas

**Comment by andreas-berg** [comment]
Also .. be aware .. there are some serious bugs in the apexchart-card since july24, I rolled back to version 2.0.4, which works..
